import React from 'react';
import { Row, Col, Layout } from 'antd';
import { BUILDING_MAX, UpgradeMode, UpgradeDetailList } from './../const.js'


import ClickingWindow from './ClickingWindow.js'
import PurchasePanel from './PurchasePanel.js'
import UpgradePanel from './UpgradePanel.js'


const { Header, Content } = Layout;




class Game extends React.Component {
  constructor(props){
    super(props);

    this.state = {
      totalSubscriber: 2000000,
      subscriberPerSecond: 0,
      buildingList: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      upgradeList: Array(730).fill(0)
    }
    this.baseSps = [0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
    this.modifiedSps = null;
    this.subscriberperclick = 0
  }


  handleMochiClick = () => {
    this.setState((prevState, props) => ({
      totalSubscriber: prevState.totalSubscriber + this.subscriberperclick
    }))
  }

  updateSubscriber = () => {
    this.setState((prevState, props) => ({
      totalSubscriber: prevState.totalSubscriber + this.state.subscriberPerSecond
    }))
  }

  calculateBaseSps = () => {
    for (let i = 1; i < BUILDING_MAX; i += 1)
    {
      let id = i;
      let base = Math.ceil((Math.pow(id * 1, id * 0.5 + 2)) * 10) / 10;
      let digits = Math.pow(10, (Math.ceil(Math.log(Math.ceil(base)) / Math.LN10))) / 100;
      base = Math.round(base / digits) * digits;
      this.baseSps[i] = base;
    }
    this.modifiedSps = this.baseSps.slice(0);
  }

  getThousandMochiBuildingCount = () => {
    const currentBuildingList = this.state.buildingList.slice(0);
    let count =currentBuildingList.reduce((pre, cur) => pre + cur, 0);
    count = count - currentBuildingList[0];
    return count;
  }

  calculateSPC = () => {
    let base = 1;
    let multiplier = 1;
    let currentUpgradeList = this.state.upgradeList.slice(0);
    if (currentUpgradeList[0] === UpgradeMode.OWNED) multiplier *= 2
    if (currentUpgradeList[1] === UpgradeMode.OWNED) multiplier *= 2
    if (currentUpgradeList[2] === UpgradeMode.OWNED) multiplier *= 2
    base = base * multiplier;

    if (currentUpgradeList[3] == UpgradeMode.OWNED)
    {
      let thousandMochiMultiplier = this.getThousandMochiBuildingCount() * 0.01;
      if (currentUpgradeList[4] === UpgradeMode.OWNED) thousandMochiMultiplier *= 5
      if (currentUpgradeList[5] === UpgradeMode.OWNED) thousandMochiMultiplier *= 10
      if (currentUpgradeList[6] === UpgradeMode.OWNED) thousandMochiMultiplier *= 20
      if (currentUpgradeList[7] === UpgradeMode.OWNED) thousandMochiMultiplier *= 20
      if (currentUpgradeList[8] === UpgradeMode.OWNED) thousandMochiMultiplier *= 20
      if (currentUpgradeList[9] === UpgradeMode.OWNED) thousandMochiMultiplier *= 20
      if (currentUpgradeList[10] === UpgradeMode.OWNED) thousandMochiMultiplier *= 20
      if (currentUpgradeList[11] === UpgradeMode.OWNED) thousandMochiMultiplier *= 20
      if (currentUpgradeList[12] === UpgradeMode.OWNED) thousandMochiMultiplier *= 20
      base = base + base * thousandMochiMultiplier;
    }

    this.subscriberperclick = base
  }



  updateSPS = (count) => {
    let sps = 0;
    this.state.buildingList.forEach((count, index) => {
      sps += this.modifiedSps[index] * count
    });
    console.log(sps);
    this.setState({
      subscriberPerSecond: sps
    });
  }



/*************************************************************************************************************
 *
 * Upgrade
 *
**************************************************************************************************************/

  /**
   * Description set buildingList and add cost to totalSubscriber
   *
   * @param {integer} index           the upgrade id or a array of upgarde list.
   */
  unlockUpgrade = (index) => {
    const newList = this.state.upgradeList.slice(0);
    let needUpdate = 0
    if (typeof(index) == 'number')
    {
      if (newList[index] === UpgradeMode.LOCK)
      {
        newList[index] = UpgradeMode.UNLOCK;
        needUpdate = 1;
      }
    }
    else if (Array.isArray(index))
    {
      for (let i = 0; i < index.length; i++)
      {
        if (newList[index[i]] === UpgradeMode.LOCK)
        {
          newList[index[i]] = UpgradeMode.UNLOCK;
          needUpdate = 1;
        }
      }
    }

    if (needUpdate === 1)
    {
      this.setState({
        upgradeList: newList,
      });
    }
    return;
  }

  handleUpgradeEffect = (index) => {
    // if the updgrade effect separated buildings sps
    // do the recaculate
    // if not, do others thing
    this.recaculateModifiedSps(index);
  }



  buyUpgrade = (index) => {
    console.log("buy index: ", index)
    const newList = this.state.upgradeList.slice(0);
    let newTotal = this.state.totalSubscriber - UpgradeDetailList[index].price;
    newList[index] = UpgradeMode.OWNED;

    this.handleUpgradeEffect(index);

    this.setState({
      upgradeList: newList,
      totalSubscriber: newTotal
    }, ()=>{
      this.updateSPS()
      this.calculateSPC()
    });

  }


  checkUpgradeUnlock = (index, amount) => {
    let indexList = [];
    console.log(index, amount);
    // check the tier upgrade
    if (index == 0)
    {
      if (amount >= 1) indexList.push(0, 1);
      if (amount >= 10) indexList.push(2);
      if (amount >= 25) indexList.push(3);
      if (amount >= 50) indexList.push(4);
      if (amount >= 100) indexList.push(4);
      if (amount >= 150) indexList.push(6);
      if (amount >= 200) indexList.push(7);
      if (amount >= 250) indexList.push(8);
      if (amount >= 300) indexList.push(9);
      if (amount >= 350) indexList.push(10);
      if (amount >= 400) indexList.push(11);
      if (amount >= 450) indexList.push(12);
    }
    else
    {
      let baseUpgradeID = 13 * index;
      if (amount >= 1) indexList.push(baseUpgradeID);
      if (amount >= 5) indexList.push(baseUpgradeID + 1);
      if (amount >= 25) indexList.push(baseUpgradeID + 2);
      if (amount >= 50) indexList.push(baseUpgradeID + 3);
      if (amount >= 100) indexList.push(baseUpgradeID + 4);
      if (amount >= 150) indexList.push(baseUpgradeID + 5);
      if (amount >= 200) indexList.push(baseUpgradeID + 6);
      if (amount >= 250) indexList.push(baseUpgradeID + 7);
      if (amount >= 300) indexList.push(baseUpgradeID + 8);
      if (amount >= 350) indexList.push(baseUpgradeID + 9);
      if (amount >= 400) indexList.push(baseUpgradeID + 10);
      if (amount >= 450) indexList.push(baseUpgradeID + 11);
      if (amount >= 500) indexList.push(baseUpgradeID + 12);
    }







    this.unlockUpgrade(indexList);
  }


/*************************************************************************************************************
 *
 * Building
 *
*************************************************************************************************************/

  /**
   * Description set buildingList and add cost to totalSubscriber
   *
   * @param {integer} index           index of buildingList.
   * @param {integer} count           amount of user buy or sell(negative).
   * @param {integer} cost            cost of buying or earn of selling.
   */
  setBuildingAmount = (index, count, cost) => {
    const newList = this.state.buildingList.slice(0);
    let newTotal = count > 0? this.state.totalSubscriber - cost: this.state.totalSubscriber + cost;
    newList[index] += count;
    if (newList[index] < 0)
    {
      newList[index] = 0;
    }
    this.checkUpgradeUnlock(index, newList[index]);
    this.updateSynergyEffectSps();

    this.setState({
      buildingList: newList,
      totalSubscriber: newTotal
    },  ()=>{
      this.updateSPS()
      this.calculateSPC()
    });

  }

  componentDidMount() {
    setInterval(this.updateSubscriber, 1000);
    this.calculateBaseSps();
  }



  render() {
    return (
      <>
        <Row wrap={false}>

          {/**Left part: clicking part and show current subscriber**/}
          <Col span={8}>
            <h1>{Math.floor( this.state.totalSubscriber )}</h1>
            <ClickingWindow subscriberperclick={this.state.subscriberperclick} handleMochiClick={this.handleMochiClick} />
          </Col>

          {/**Middle part: news, some buttons, and show the image for every upgrade**/}

          <Col span={8}>
            <Layout>
              <Content style={{ overflow: 'scroll' }} >
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
                middleYesterdayDay, my wife and I watched thethis filmmovie, For Here or To GoStart? atin our local San Francisco theaterhouse. SetMade in 2009, thethis filmmovie is one of the first bilingual filmsmovies to be nationally releasedissued inat the U.S. It tells the storytale of high-skilled immigrants and thethose challenges & emotions they goget through with their lives — from lovepassion, entrepreneurship, acceptancetolerance, assimilationabsorption and hatehatred. Depicting multiple generations, thethis filmmovie does a masterful jobwork of making people laugh, thinkbelieve and empathizeunderstand. This is athe rare entrepreneurial effortendeavor by first-time filmmakerproducer and full-time Gap employeeworker Rishi. In 2010, Rishi taughtlearnt himself screenwriting through Google and 7 years laterafter seesrealizes the fruits of his laborwork on 29 biglarge screens across thethis nationcountry. We couldwould n't be more proud of thisthe filmmovie, as it tellssays the immigrant story through athe lens seldomrarely seen — authenticgenuine and light-hearted.
              </Content>
            </Layout>
          </Col>

          {/**Right part: upgrade pannel**/}
          <Col span={8} style={{ overflow: 'auto' }}>
            <UpgradePanel upgradeList={this.state.upgradeList} totalSubscriber={this.state.totalSubscriber} buyUpgrade={this.buyUpgrade}/>
            <PurchasePanel totalSubscriber={this.state.totalSubscriber} buildingList={this.state.buildingList} setBuildingAmount={this.setBuildingAmount} />
          </Col>
        </Row>
      </>
    )
  }
}

export default Game;
